#!/usr/bin/env bash
# Configure Nginx, and setting up the HTTP response to have a custom header Served-By: $HOSTNAME.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
echo 'Hello World!' |sudo tee /var/www/html/index.html
echo 'Ceci n'est pas une page' |sudo tee /var/www/html/404.html

custom_header="server_name _;\n\tadd_header X-Served-By \$HOSTNAME;"
sudo sed -i "s|server_name _;|$custom_header|" /etc/nginx/sites-enabled/default

sudo service nginx restart
