#!/usr/bin/env bash
# Accepts 4 parameters. The path to the file to be transferred. The IP of the server we want to transfer the file to. The username scp connects with. The path to the SSH private key that scp uses

if [ $# -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if scp -i "PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "PATH_TO_FILE" "USERNAME"@"IP":~/; then
echo "File transferred successfully"
else
echo "File transfer failed." >&2
exit 1
fi
# scp -i ~/.ssh/school -o StrictHostKeyChecking=no some_page.html ubuntu@18.212.50.164:~/