#!/usr/bin/env bash
# Script that configures Nginx to a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx

sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'

echo 'Holberton School' | sudo tee /var/www/html/index.html

sudo service nginx restart