#!/usr/bin/env bash
# Commands to automatically configure a Ubuntu machine to handle redirection

sudo apt-get -y update
sudo apt-get -y install nginx

sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'

sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart