#!/usr/bin/env bash
# script that install nginx and configure it to redirect to another page when
# accessing the /redirect_me page.
sudo apt update -y
sudo apt install nginx -y

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
# store configuration content
new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        location /redirect_me { 
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
"
echo "$new_config" > /etc/nginx/sites-available/default
sudo service nginx restart

# #!/usr/bin/env bash
# # Commands to automatically configure a Ubuntu machine to handle redirection

# sudo apt-get update
# sudo apt-get install nginx

# sudo ufw allow 'Nginx HTTP'

# echo "Holberton School" | sudo tee /var/www/html/index.html

# sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# sudo service nginx restart