#!/usr/bin/env bash
# Commands to automatically configure a Ubuntu machine to handle 404 error

sudo apt update -y
sudo apt install nginx -y

sudo touch /var/www/html/404.html
sudo sed -i '/server_name _;/a error_page 404 /404.html' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart

