#!/usr/bin/env bash
# Commands to automatically configure a Ubuntu machine to handle 404 error

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo touch /var/www/html/error_404.html
sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo service nginx restart