#!/usr/bin/env bash
# Commands to automatically configure a Ubuntu machine to handle 404 error

sudo apt-get -y update
sudo apt-get -y install nginx

sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart

